services:
  app:
    build: .
    container_name: whatsrunning-app
    ports:
      - "2009:3000"
      - "8001:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /DATA/AppData/nginxproxymanager/data:/data:ro
    networks:
      - whatsrunning_network
    restart: unless-stopped

networks:
  whatsrunning_network:
    driver: bridge
